Finish him!
fintarin/Fintamath pull request #112
Opened 2023-03-20 10:04 UTC by ProtasSemyon

2023-04-20 18:39 UTC, fintarin requested changes

2023-04-20 18:39 UTC, fintarin commented on tests/src/expressions/IExpressionTests.cpp
> -// TODO add tests for all public functions
Написать тесты для всех этих функций

2023-04-20 18:39 UTC, fintarin commented on tests/src/expressions/ExpressionTests.cpp
> +  // TODO: The problem here is that 1/2 and 1/3 are Expressions not Rationals
Пофиксить сортировку

2023-04-20 18:39 UTC, fintarin commented on tests/src/expressions/ExpressionTests.cpp
> +  EXPECT_EQ(Expression("(5+b)/a*(a+3)/(b+2)").toString(),
Пофиксить сортировку

2023-04-20 18:39 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  shared_ptr<const IExpression> setValuesOfVariables(const ArgumentsPtrVector &vars,
Перенести это в Expression

2023-04-20 18:39 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  static void copyPropertiesToChild(ArgumentPtr &lhs, const ArgumentPtr &rhs);
Можно убрать

2023-04-20 18:39 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  virtual ArgumentPtr copyPropertiesAbstract(const ArgumentPtr &rhs) const = 0;
Можно убрать

2023-04-20 18:39 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  ArgumentPtr copyPropertiesAbstract(const ArgumentPtr &rhs) const final {
Можно убрать

2023-04-20 18:39 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  virtual void copyProperties(const Derived & /*rhs*/) {
Можно убрать

2023-04-20 18:39 UTC, fintarin commented on src/fintamath/expressions/unary/InvExpression.cpp
> +    auto error = Integer(1) / Integer(0);
throw UndefinedBinaryOperatorException

2023-04-20 18:39 UTC, fintarin commented on src/fintamath/expressions/unary/InvExpression.cpp
> +    auto error = Integer(1) / Integer(0);
throw UndefinedBinaryOperatorException

2023-04-21 07:54 UTC, ProtasSemyon commented on include/fintamath/expressions/IExpression.hpp
> +  shared_ptr<const IExpression> setValuesOfVariables(const ArgumentsPtrVector &vars,
Могу в принципе сделать этот метод протектед, а публичный будет в Expression

2023-04-21 14:45 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  shared_ptr<const IExpression> setValuesOfVariables(const ArgumentsPtrVector &vars,
Оставляй здесь, но сделай неконстантным void методом

2023-04-21 20:26 UTC, fintarin requested changes

2023-04-21 20:26 UTC, fintarin commented on src/fintamath/expressions/binary/CompExpression.hpp
> +  void copyProperties(const CompExpression &rhs) override;
Можно убрать

2023-04-23 12:13 UTC, fintarin requested changes

2023-04-23 12:13 UTC, fintarin commented on include/fintamath/expressions/IPolynomExpression.hpp
> +  virtual FunctionsVector getSimplifyFunctions() const;
Название не очень нравится, но не знаю, как лучше назвать

2023-04-23 12:13 UTC, fintarin commented on src/fintamath/expressions/polynomial/SumExpression.hpp
> +  string childToString(const ArgumentPtr &child, bool isFirst = false) const override;
protected

2023-04-23 12:13 UTC, fintarin commented on src/fintamath/expressions/polynomial/SumExpression.cpp
> +  if (lhsChildValue->toString() == rhsChildValue->toString()) {
*lhsChildValue == *rhsChildValue

2023-04-23 12:13 UTC, fintarin commented on include/fintamath/expressions/IPolynomExpression.hpp
> +  virtual string childToString(const ArgumentPtr &child, bool isFirst = false) const;
Выглядит, что isFirst не нужен во всех случаях, стоит перенести эту логику в IPolynomExpression::toString()

2023-04-23 12:13 UTC, fintarin commented on src/fintamath/expressions/polynomial/IPolynomExpression.cpp
> +  if (result.empty()) {
Какой-то костыль, сюда не должно заходить, надо убрать

2023-04-24 12:38 UTC, ProtasSemyon commented on include/fintamath/expressions/IPolynomExpression.hpp
> +  virtual string childToString(const ArgumentPtr &child, bool isFirst = false) const;
см childToString в SumExpression и childToString в MulExpression

2023-04-24 12:39 UTC, ProtasSemyon commented on include/fintamath/expressions/IPolynomExpression.hpp
> +  virtual string childToString(const ArgumentPtr &child, bool isFirst = false) const;
О, и в OrExpression

2023-04-24 13:46 UTC, fintarin commented on include/fintamath/expressions/IPolynomExpression.hpp
> +  virtual string childToString(const ArgumentPtr &child, bool isFirst = false) const;
Видел, но можно нигде не выводить первый оператор

2023-04-24 15:53 UTC, fintarin requested changes

2023-04-24 15:53 UTC, fintarin commented on src/fintamath/expressions/polynomial/MulExpression.cpp
> +  bool isLhsInverted = false;
Попробовать перенести это в IPolynomExpression

2023-04-24 15:53 UTC, fintarin commented on src/fintamath/expressions/polynomial/SumExpression.cpp
> +  bool lhsNeg = false;
Попробовать перенести это в IPolynomExpression

2023-04-24 15:53 UTC, fintarin commented on include/fintamath/expressions/IExpression.hpp
> +  ArgumentPtr setValuesOfVariables(const ArgumentsPtrVector &vars, const ArgumentsPtrVector &vals) const;
Можно переименовать и сделать friend

2023-04-24 16:20 UTC, fintarin commented on tests/src/expressions/IExpressionTests.cpp
> +TEST(IExpressionTests, getFunctionTest) {
Добавить тесты

2023-04-25 10:06 UTC, fintarin commented on tests/src/expressions/ExpressionTests.cpp
> +  // TODO: add tests
Добавить тесты

2023-04-25 10:06 UTC, fintarin commented on tests/src/expressions/ExpressionTests.cpp
> +  // TODO: add tests
Добавить тесты

2023-04-26 22:09 UTC, fintarin commented on src/fintamath/expressions/polynomial/MulExpression.cpp
> +  return {
Пофифксить зацикливания. Надо, чтобы можно было закомментить любую из функций без зацикливаний

2023-04-26 22:10 UTC, fintarin commented on src/fintamath/expressions/polynomial/SumExpression.cpp
> +  return {
Пофифксить зацикливания. Надо, чтобы можно было закомментить любую из функций без зацикливаний

2023-04-26 22:31 UTC, fintarin commented on src/fintamath/expressions/polynomial/MulExpression.cpp
> +  switch (mulChildren.size()) {
Сделать, чтобы выводилилось в виде (x y z)/(a b c)

2023-04-27 09:03 UTC, fintarin commented on src/fintamath/expressions/IPolynomExpression.cpp
> +void IPolynomExpression::globalSimplifyRec() {
Переименовать

2023-04-27 11:55 UTC, fintarin commented on include/fintamath/expressions/IPolynomExpression.hpp
> +  virtual string childToString(const ArgumentPtr &inChild, bool isFirst = false) const = 0;
Попробовать убрать isFirst

2023-04-27 17:25 UTC, fintarin commented on src/fintamath/expressions/polynomial/IPolynomExpression.cpp
> +
Название плохое, оно вообще не сравнивает полиномы

2023-04-28 08:33 UTC, fintarin commented on src/fintamath/expressions/polynomial/SumExpression.cpp
> +  return {
Пофифксить зацикливания. Надо, чтобы можно было закомментить любую из функций без зацикливаний

2023-04-28 08:33 UTC, fintarin commented on src/fintamath/expressions/polynomial/MulExpression.cpp
> +  return {
Пофифксить зацикливания. Надо, чтобы можно было закомментить любую из функций без зацикливаний

2023-04-28 08:39 UTC, fintarin commented on tests/src/expressions/IExpressionTests.cpp
> +TEST(IExpressionTests, getFunctionTest) {
Добавить тесты

2023-04-28 13:22 UTC, fintarin commented on tests/src/expressions/ExpressionUtilsTests.cpp
> +TEST(ExpressionUtilsTests, skipBracketsTest) {
Добавить тесты

2023-04-28 14:16 UTC, fintarin commented on src/fintamath/expressions/binary/PowExpression.hpp
> +  // start set of methods for Multinomial theorem
Перенести комменты в cpp

2023-04-28 14:16 UTC, fintarin commented on src/fintamath/expressions/binary/PowExpression.cpp
> +Integer PowExpression::generateNextNumber(Integer n) {
Добавить комменты к алгоритму

2023-04-28 14:17 UTC, fintarin commented on src/fintamath/expressions/binary/PowExpression.cpp
> +Integer PowExpression::generateFirstNum(const Integer &countOfOne) {
Добавить комменты к алгоритму

2023-04-28 14:17 UTC, fintarin commented on src/fintamath/expressions/binary/PowExpression.cpp
> +vector<Integer> PowExpression::generateSplit(Integer bitNumber, const Integer &variableCount) {
Добавить комменты к алгоритму

2023-04-28 17:27 UTC, fintarin commented on tests/src/numbers/IntegerFunctionsTests.cpp
> +  // TODO: add tests
Добавить тесты

2023-04-28 17:27 UTC, fintarin commented on tests/src/numbers/IntegerFunctionsTests.cpp
> +  // TODO: add tests
Добавить тесты

2023-04-28 21:30 UTC, fintarin commented on src/fintamath/expressions/polynomial/MulExpression.cpp
> +      &MulExpression::simplifyNegations, //
Некоторые функции можно сделать только в pre или post simplify

2023-04-29 22:36 UTC, fintarin approved these changes

2023-04-30 00:14 UTC, merged