Expression parsing implementation
fintarin/Fintamath pull request #36
Opened 2022-02-25 18:56 UTC by Semen-proger

2022-02-25 22:01 UTC, fintarin requested changes

2022-02-25 22:01 UTC, fintarin commented on include/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.hpp
> +    static void ignoreBrackets(const std::string_view &str, int &position);
Move from header to src

2022-02-25 22:01 UTC, fintarin commented on include/fintamath/math_objects/relations/RelationParser.hpp
>  #include "fintamath/math_objects/relations/Relation.hpp"
Remove

2022-02-25 22:01 UTC, fintarin commented on include/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.hpp
> +#include "fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperator.hpp"
Remove

2022-02-25 22:01 UTC, fintarin commented on include/fintamath/math_objects/relations/operators/arithmetic_operators/unary_arithmetic_operators/UnaryArithmeticOperatorParser.hpp
> +#include "fintamath/math_objects/relations/operators/arithmetic_operators/unary_arithmetic_operators/UnaryArithmeticOperator.hpp"
Remove

2022-02-25 22:01 UTC, fintarin commented on include/fintamath/math_objects/relations/operators/arithmetic_operators/ArithmeticOperatorParser.hpp
> +#include "fintamath/math_objects/relations/operators/arithmetic_operators/ArithmeticOperator.hpp"
Remove

2022-02-25 22:01 UTC, fintarin commented on include/fintamath/math_objects/MathObjectParser.hpp
> +    static std::string_view deleteOpenAndCloseBracket(const std::string_view &str);
Move to Expression src

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/nodes/expressions/Expression.cpp
> +    throw std::invalid_argument("Expression invalid argument");
Remove changes

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/nodes/expressions/Expression.cpp
> +  Expression::Expression(const Set &set, const std::shared_ptr<Relation> &relation)
Indent after closing brackets

Fix clang-tidy warnings

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/nodes/expressions/Expression.cpp
> +
Remove indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +  }
Indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +  std::unique_ptr<Expression> BinaryArithmeticOperatorParser::parse(const std::string_view &str) {
Fix clang-tidy warning

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +    for (int i = str.size() - 1; i >= 0; i--) {
Fix clang-tidy warning

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +    auto plusSign = BinaryPlus().toString();
Let's use `auto plusSign = BinaryPlus().toString()[0]`. It will be easier for comparisons

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +        }
Indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +
Remove indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +        auto secondOperandStr = str.substr(i + 1);
Don't create these variables

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +
Remove indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +        Set set{firstOperand, secondOperand};
Add indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +          relation = std::make_shared<BinaryPlus>();
Let's create getters and setters in Expression, and just create a new Expression a few lines before, instead of Set and Relation

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +    for (int i = str.size() - 1; i >= 0; i--) {
Fix clang-tidy warning

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +          throw std::invalid_argument("Expression invalid input");
Create const for this string

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +        if (str[i - 1] == plusSign[0]) {
Use switch case

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/unary_arithmetic_operators/UnaryArithmeticOperatorParser.cpp
> +    if (str.size() == 0) {
`str.empty()`

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/unary_arithmetic_operators/UnaryArithmeticOperatorParser.cpp
> +    if (str[0] == UnaryMinus().toString().at(0) || str[0] == UnaryPlus().toString().at(0)) {
`UnaryMinus().toString()[0]`

And let's create variables for operators

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/unary_arithmetic_operators/UnaryArithmeticOperatorParser.cpp
> +      auto operandStr = str.substr(1, str.size() - 1);
Remove this variable

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/unary_arithmetic_operators/UnaryArithmeticOperatorParser.cpp
> +      return std::make_unique<Expression>(set, relation);
Create Expression as in BinaryArithmeticOperatorParser

And indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/ArithmeticOperatorParser.cpp
> +    if(auto res = BinaryArithmeticOperatorParser::parse(str);res){
Format

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/RelationParser.cpp
>  #include "fintamath/math_objects/nodes/terms/TermParser.hpp"
Remove

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/relations/RelationParser.cpp
>  #include <stdexcept>
Remove

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
> +    int leftBracket = 0;
Indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
> +    int position = 0;
Indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
> +    if (position == str.size()) {
Indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
> +    return str;
Indent

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
> +      if (str[position] == ')') {
else if

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
>    std::unique_ptr<MathObject> MathObjectParser::parse(const std::string_view &str) {
Remove this variable

2022-02-25 22:01 UTC, fintarin commented on src/fintamath/math_objects/MathObjectParser.cpp
> +    std::string_view strForParsing = deleteOpenAndCloseBracket(str);
auto

2022-02-25 22:01 UTC, fintarin commented on tests/src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParserTests.cpp
> +}
Format

2022-02-26 21:03 UTC, ProtasSemyon commented on src/fintamath/math_objects/relations/operators/arithmetic_operators/binary_arithmetic_operators/BinaryArithmeticOperatorParser.cpp
> +  std::unique_ptr<Expression> BinaryArithmeticOperatorParser::parse(const std::string_view &str) {
https://www.youtube.com/watch?v=WL0LVGAF1js

2022-03-30 13:27 UTC, closed without merging